### ISSUE TITLE
Can not show the picture in the firebase 

### ISSUE THREAD

**Issue by quangLH195** [JeffKi11er/SEProjectGROUP22#1]
I did try and found this 
![image](https://user-images.githubusercontent.com/59214933/79068519-ba226400-7cf1-11ea-99b3-52035a82c3d7.png)
[You can find it here](https://stackoverflow.com/questions/55547642/image-not-retrieving-from-firebase)
**Maybe it caused by children**

**Comment by JeffKi11er** [comment]
I just forgot
I did fix this bug yet
