### ISSUE TITLE
Can not open the viewpager

### ISSUE THREAD

**Issue by quangLH195** [JeffKi11er/SEProjectGROUP22#12]
It's showing on the screen that I can not use the tab layout

**Comment by quangLH195** [comment]
Ah I forgot the screen capture

**Comment by JeffKi11er** [comment]
I see, did you use the RelativeLayout ?

**Comment by quangLH195** [comment]
What's the problem with that?

**Comment by JeffKi11er** [comment]
You need to change into **LinearLayout**, which is the entire screen

**Comment by JeffKi11er** [comment]
It's hard to explain but it seems work with me
![image](https://user-images.githubusercontent.com/45094606/79899806-7c32e780-8437-11ea-9dbc-840d938d0784.png)

**Comment by quangLH195** [comment]
Ok it's seem right

**Comment by JeffKi11er** [comment]
ok, fixed !

**Comment by JeffKi11er** [comment]
6b49e4c8f9773e1324b517c25d81d40beb12eea7
