### ISSUE TITLE
Redesign home screen layout

### ISSUE THREAD

**Issue by quangLH195** [JeffKi11er/SEProjectGROUP22#13]
Applying the same design of the old home screen's design, I want to change this things :
* **ViewPager**
* **TabLayout**
to
**BottomNavigationLayout**
All in commit 6b49e4c8f9773e1324b517c25d81d40beb12eea7 
The following design 
![artboard___2_2x](https://user-images.githubusercontent.com/59214933/80279025-1a1efe80-8725-11ea-88e3-024ff66f92dc.png)

**Comment by JeffKi11er** [comment]
The result :
![image](https://user-images.githubusercontent.com/45094606/80281832-2f515880-8738-11ea-90c5-8f18ffe51736.png)
![image](https://user-images.githubusercontent.com/45094606/80281929-c0283400-8738-11ea-80df-b81f40109ceb.png)
