### ISSUE TITLE
Ok, I did find the way to uploading image more efficiently 

### ISSUE THREAD

**Issue by JeffKi11er** [JeffKi11er/SEProjectGROUP22#8]
[Take a look at that](https://github.com/JeffKi11er/FireBaseImageRecycleView/commit/37a397e55522b7cffd64a5133f716924fca64025)
This way we change the way to upload image into the storage and also the way to get the image data
**not using Glide but using Picasso library**
**¯\_(ツ)_/¯**

**Comment by quangLH195** [comment]
quite complicated, right ?

**Comment by JeffKi11er** [comment]
not really,
just set like that
**with database**
![image](https://user-images.githubusercontent.com/45094606/79147404-12d72700-7dee-11ea-8d57-3617d3f80cc6.png)
**and with storage**
![image](https://user-images.githubusercontent.com/45094606/79147525-431ec580-7dee-11ea-9666-a754b5ee7e96.png)

**Comment by quangLH195** [comment]
we didn't do that things 
![91374398_1862325563900465_4338195716632477696_n](https://user-images.githubusercontent.com/59214933/79147776-add00100-7dee-11ea-9095-4ee7fc18e720.jpg)

**Comment by quangLH195** [comment]
So what about the result

**Comment by JeffKi11er** [comment]
![image](https://user-images.githubusercontent.com/45094606/79148288-731a9880-7def-11ea-88c2-6c3b76ccfc7d.png)
![image](https://user-images.githubusercontent.com/45094606/79148383-95141b00-7def-11ea-8ae4-6b1a56a76f47.png)
![image](https://user-images.githubusercontent.com/45094606/79148472-b4ab4380-7def-11ea-8f85-a880ea860adf.png)

**Comment by JeffKi11er** [comment]
did by using JSON also

**Comment by quangLH195** [comment]
Keep it up
