### ISSUE TITLE
I did change successfully the way to upload image in firebase

### ISSUE THREAD

**Issue by JeffKi11er** [JeffKi11er/SEProjectGROUP22#9]
**I just create it like a child of database realtime**
[Check it out](https://github.com/JeffKi11er/SEProjectGROUP22/blob/master/app/src/main/java/com/example/uibeautifulcollection2/ProfileActivity.java)
![image](https://user-images.githubusercontent.com/45094606/79215042-5b85f300-7e75-11ea-9728-6cbf30b76b5b.png)
[The link is here](https://uibeautifulcollection2.firebaseio.com/)

**Comment by quangLH195** [comment]
ok nice
